FROM python:3.11-alpine
RUN apk add --no-cache bash
RUN pip install flask requests --no-cache-dir --break-system-packages
COPY ./agents/daemon_messenger.py /usr/local/bin/mlswarm-daemon.py
COPY ./agents/local-agent.py /usr/local/bin/mlswarm-agent.py
COPY ./agents/local-ascii.py /usr/local/bin/mlswarm-ascii.py
COPY ./agents/claude_agent.py /usr/local/bin/mlswarm-claude-agent.py
COPY ./agents/agent_entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENV PYTHONUNBUFFERED=1
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]