FROM nginx:alpine

RUN mkdir -p /var/www/swarms
COPY ./nginx/http.nginx.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/swarm.html /var/www/swarms/index.html
RUN chown -R nginx:nginx /var/www/swarms

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]