FROM nginx:alpine

COPY http.nginx.conf /etc/nginx/conf.d/default.conf
COPY swarm.html /var/www/swarm/index.html

RUN mkdir -p /var/www/swarm
RUN chown -R nginx:nginx /var/www/swarm

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]